MultiApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.hero.urls', namespace='heroes')),
    url(r'^power/', include('apps.power.urls', namespace='powers'))
]

apps/hero/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^(?P<id>\d+)$', views.show, name='show'),
    url(r'^(?P<hero_id>\d+)/addpower$', views.add_power, name='add_power')
]

apps/power/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # localhost:8000/power
    url(r'^$', views.index, name='index'),
    url(r'^create', views.create, name="create"),
    url(r'^(?P<id>\d+)$', views.show, name='show')

]

apps/hero/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..power.models import Power
from django.db import models

# Create your models here.
# class Power(models.Model):
#     name = models.CharField(max_length=100)
#     power_level = models.IntegerField()

class HeroManager(models.Manager):
    def create_valid(self, postdata):
        """
        Returns tuple: (is_valid, [errors])
        """
        errors = []
        is_valid = True 
        if len(postdata['name']) < 1:
            errors.append("Name field is required")
            is_valid = False
        if is_valid:
            self.create(
                name = postdata['name']
            )
        return (is_valid, errors)

class Hero(models.Model):
    name = models.CharField(max_length=100)
    powers = models.ManyToManyField(Power, related_name="heros")
    objects = HeroManager()
    def __str__(self):
        return self.name

apps/power/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Power(models.Model):
    name = models.CharField(max_length=100)
    power_level = models.IntegerField()
    #heroes => [Hero]

    def __str__(self):
        return self.name

apps/hero/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Hero
from ..power.models import Power
from django.contrib import messages
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect

# Create your views here.
def index(req):
    context = {
        'heroes': Hero.objects.all()
    }
    return render(req, "hero/index.html", context)

def show(req, id):
    context = {
        "hero": Hero.objects.get(id=id),
        "powers": Power.objects.all()
    }
    return render(req, 'hero/show.html', context)

def create(req):
    valid = Hero.objects.create_valid(req.POST)
    if not valid[0]:
        for error in valid[1]:
            messages.error(req, error)
    return HttpResponseRedirect(reverse("heroes:index"))

def add_power(req, hero_id):
    the_hero = Hero.objects.get(id=hero_id)
    the_power = Power.objects.get(id=req.POST['power'])
    the_hero.powers.add(the_power)
    return HttpResponseRedirect(reverse("heroes:index"))

apps/power/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Power
from django.shortcuts import render, HttpResponseRedirect, reverse

# Create your views here.
def index(req):
    context = {
        'powers': Power.objects.all()
    }
    return render(req, 'power/index.html', context)

def create(req):
    Power.objects.create(
        name=req.POST['name'],
        power_level=req.POST['level']
    )
    return HttpResponseRedirect(reverse("powers:index"))
def show(req, id):
    context = {
        "power": Power.objects.get(id=id)
    }
    return render(req, 'power/show.html', context)

apps/hero/templates/hero/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>HEROS</h1>
        <ul>
        {% for hero in heroes %}
            <li><a href="/{{ hero.id }}">{{ hero }}</a></li>
        {% endfor %}
        </ul>
        <hr>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <h4>Add a hero:</h4>
        <form action='{% url "heroes:create" %}' method="POST">{% csrf_token %}
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" name="name">
                <input type="submit" value="Add">
            </div>
        </form>
    </body>
</html>

apps/hero/templates/hero/show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>{{ hero }}</h1>
        <hr>
        <h3>has powers:</h3>
        <ul>
            {% for power in hero.powers.all %}
            <li>{{ power }}</li>
            {% endfor %}
        </ul>
        <form action="{% url 'heroes:add_power' hero.id %}" method="POST">{% csrf_token %}
            <select name='power'>
                {% for pow in powers %}
                <option value="{{ pow.id }}">{{ pow }}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Add Power to Hero">
        </form>
    </body>
</html>

apps/power/templates/power/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>POWERRR</h1>
        <ul>
        {% for pow in powers %}
            <li><a href="/{{ pow.id }}">{{ pow }}</a></li>
        {% endfor %}
        </ul>
        <hr>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <h4>Add a POWER:</h4>
        <form action='{% url "powers:create" %}' method="POST">{% csrf_token %}
            <div class="form-group">
                <label for="name">Power Name:</label>
                <input type="text" name="name">
            </div>
             <div class="form-group">
                <label for="level">POWER LEVEL:</label>
                <input type="number" name="level">
            </div>
            <input type="submit" value="Add">
        </form>
    </body>
</html>

apps/power/templates/power/show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>{{ power }}</h1>
        <hr>
    </body>
</html>